name: wq-data-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - pyarrow=16.*
  - scipy=1.13.*
  - pip
  - pip:
      - saqc==0.7.3

